### PR TITLE
Updated to use 'openshift-applier' v2.0.0

### PR DESCRIPTION
**Pull request by oybed**
Updating to use the latest [v2.0.0](https://github.com/redhat-cop/openshift-applier/releases/tag/v2.0.0) version of the [openshift-applier](https://github.com/redhat-cop/openshift-applier).

### CODE REVIEW

**Comment by oybed** [comment]
Related docs change PR: https://github.com/rht-labs/enablement-docs/pull/262

**Comment by syvanen** [comment]
These files also exist in other branches. Any plans on how to get them updated?

**Comment by oybed** [comment]
Good question for @springdo - what's the plan/process in place to ensure all branches get updated (sounds like we need some docs around this in contribution guide)

**Comment by oybed** [comment]
Also, since this PR has been open since August, it should be updated to move to a much later version of the `openshift-applier` - i.e.: `v2.0.9`. I'll see if I can find some time to get this done. 

Did I hear optimistic merging somewhere? ;-)

**Comment by oybed** [comment]
Too late -closing

**Pull request closed without merging**
